-- 1. How to select presidents with cool names?
--      - Cool names are when their name.length < 9
--      - Okay names are when 9 <= name.length < 16
--      - Bad names are when 16 <= name.length

-- 2. How to select currently alive prime ministers?
-- 3. How to select prime ministers who were in office before 1915?
-- 4. How to select prime ministers who were in office before 1915 and after 1776?
-- 5. How to select prime ministers who have the word 'in' in their name?
-- 6. Of the presidents that are not alive, who were the oldest 10?
-- 7. Of the presidents that are not alive, who were the youngest 10?
